#!/bin/bash
# axis: session-end projection refresh + data-plane manifest reconcile
# Generated by axis — regenerate via `axis sync`
command -v axis >/dev/null 2>&1 || exit 0
# Same drift guard as session start: never clobber a hand-edit silently.
if axis doctor --projection >/dev/null 2>&1; then
  axis sync --quiet 2>/dev/null
else
  echo "⚠ Hand-edited projected files — sync skipped (axis doctor --projection)"
fi
if [ -f .ai/data.yaml ]; then
  axis data sync 2>/dev/null | grep -v '^$'
fi
exit 0
