#!/bin/bash
# axis: session-end projection refresh + data-plane manifest reconcile
# Generated by axis — regenerate via `axis sync`
command -v axis >/dev/null 2>&1 || exit 0
axis sync --quiet 2>/dev/null
if [ -f .ai/data.yaml ]; then
  axis data sync 2>/dev/null | grep -v '^$'
fi
exit 0
