#!/bin/bash
# axis: Auto-sync + load memory at session start
# Generated by axis — edit .ai/hooks/session-start.md instead
if command -v axis >/dev/null 2>&1; then
  # Drift meter first: if a generated file was hand-edited, auto-sync would
  # clobber it — surface that instead of syncing (exit 1 = hand-edit drift).
  if axis doctor --projection >/dev/null 2>&1; then
    axis sync --quiet 2>/dev/null
  else
    echo "⚠ Hand-edited projected files detected — auto-sync SKIPPED."
    axis doctor --projection 2>/dev/null
    echo "Move the edit into .ai/ source and run 'axis sync', or run 'axis sync' to discard it."
  fi
fi

ATLAS_DIR=".ai/memory"
MEMORY="${ATLAS_DIR}/MEMORY.md"
USER_MD="${ATLAS_DIR}/USER.md"
TODAY=$(date +%Y-%m-%d)
DAILY="${ATLAS_DIR}/daily/${TODAY}.md"

[ -f "$MEMORY" ] && cat "$MEMORY"
[ -f "$USER_MD" ] && cat "$USER_MD"
[ -f "$DAILY" ] && cat "$DAILY"

# Data plane: orient the session — binding health + anything waiting in Inbox.
# (A crashed prior session may have left manifests stale; reconcile is cheap
# and stat-only, so run it here too rather than only at Stop.)
if [ -f .ai/data.yaml ] && command -v axis >/dev/null 2>&1; then
  axis data sync 2>/dev/null | grep -v '^$'
  axis data status 2>/dev/null | grep -v '^$'
fi
