#!/bin/bash
# axis: Auto-sync + load memory at session start
# Generated by axis — edit .ai/hooks/session-start.md instead
command -v axis >/dev/null 2>&1 && axis sync --quiet 2>/dev/null

ATLAS_DIR=".ai/memory"
MEMORY="${ATLAS_DIR}/MEMORY.md"
USER_MD="${ATLAS_DIR}/USER.md"
TODAY=$(date +%Y-%m-%d)
DAILY="${ATLAS_DIR}/daily/${TODAY}.md"

[ -f "$MEMORY" ] && cat "$MEMORY"
[ -f "$USER_MD" ] && cat "$USER_MD"
[ -f "$DAILY" ] && cat "$DAILY"
