// axis: Transcript capture hook for Claude Code
// Generated by axis — edit .ai/hooks/transcript-capture.md instead
const fs = require('fs');
const path = require('path');

const input = JSON.parse(fs.readFileSync('/dev/stdin', 'utf8'));

if (input.stop_reason === 'end_turn' && input.response) {
  const today = new Date().toISOString().slice(0, 10);
  const time = new Date().toISOString().slice(11, 19);
  const dir = path.join(process.env.CLAUDE_PROJECT_DIR || '.', '.ai', 'memory', 'transcripts');
  const file = path.join(dir, `${today}.md`);

  try {
    fs.mkdirSync(dir, { recursive: true });
    const summary = input.response.slice(0, 500).replace(/\n{3,}/g, '\n\n');
    const entry = `\n## ${time}\n${summary}\n`;
    fs.appendFileSync(file, entry);
  } catch (e) {
    // Fire and forget — don't break the session
  }
}
