// axis session lifecycle plugin
// Generated by axis — edit .ai/ source instead

import { readFileSync, appendFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";

export default async ({ directory }: { directory: string }) => {
  const contextDir = join(directory, ".ai", "memory");

  const readIfExists = (path: string): string => {
    try { return existsSync(path) ? readFileSync(path, "utf8") : ""; }
    catch { return ""; }
  };

  const today = () => new Date().toISOString().slice(0, 10);
  const now = () => new Date().toISOString().slice(11, 19);

  return {
    // Auto-sync + inject memory context at session start
    "session.created": async () => {
      try {
        const { execSync } = await import("child_process");
        execSync("axis sync --quiet", { cwd: directory, stdio: "ignore", timeout: 10000 });
      } catch { /* axis not installed or sync failed — continue */ }
    },
    "chat.params": async (_input: any, output: any) => {
      const memory = readIfExists(join(contextDir, "MEMORY.md"));
      const user = readIfExists(join(contextDir, "USER.md"));
      const daily = readIfExists(join(contextDir, "daily", `${today()}.md`));
      const context = [memory, user, daily].filter(Boolean).join("\n\n---\n\n");
      if (context && output.system) {
        output.system += "\n\n" + context;
      }
    },
    // Capture transcript summaries
    "tool.execute.after": async (input: any) => {
      try {
        const dir = join(contextDir, "transcripts");
        mkdirSync(dir, { recursive: true });
        const file = join(dir, `${today()}.md`);
        const summary = String(input.output || "").slice(0, 500)
          .replace(/\n{3,}/g, "\n\n");
        if (summary) {
          appendFileSync(file, `\n## ${now()}\n${summary}\n`);
        }
      } catch { /* fire and forget */ }
    },
  };
};
